apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-sa
  namespace: inventory-system
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::<AWS_ACCOUNT_ID>:role/inventory-system-backend-role
